package com.bsoft.wechat;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.3
 * 2018-05-22T17:19:26.823+08:00
 * Generated source version: 3.2.3
 *
 */
@WebService(targetNamespace = "http://www.bsoft.com.cn/webservices/", name = "ServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ServiceSoap {

    /**
     * 【数据交换平台】
     */
    @WebMethod(operationName = "MainWebInterface", action = "http://www.bsoft.com.cn/webservices/MainWebInterface")
    @RequestWrapper(localName = "MainWebInterface", targetNamespace = "http://www.bsoft.com.cn/webservices/", className = "com.bsoft.wechat.MainWebInterface")
    @ResponseWrapper(localName = "MainWebInterfaceResponse", targetNamespace = "http://www.bsoft.com.cn/webservices/", className = "com.bsoft.wechat.MainWebInterfaceResponse")
    @WebResult(name = "MainWebInterfaceResult", targetNamespace = "http://www.bsoft.com.cn/webservices/")
    public java.lang.String mainWebInterface(
        @WebParam(name = "DbType", targetNamespace = "http://www.bsoft.com.cn/webservices/")
        java.lang.String dbType,
        @WebParam(name = "OrgId", targetNamespace = "http://www.bsoft.com.cn/webservices/")
        java.lang.String orgId,
        @WebParam(name = "UserId", targetNamespace = "http://www.bsoft.com.cn/webservices/")
        java.lang.String userId,
        @WebParam(name = "PassWord", targetNamespace = "http://www.bsoft.com.cn/webservices/")
        java.lang.String passWord,
        @WebParam(name = "MethordName", targetNamespace = "http://www.bsoft.com.cn/webservices/")
        java.lang.String methordName,
        @WebParam(name = "InXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
        java.lang.String inXML
    );
}
